---
- name: install sssd-clients
  yum:
    name: sssd-client
    state: 'present'
  when:
    - os_auth_pam_sssd_enable | bool

- name: install the package for strong password checking
  yum:
    name: 'pam_passwdqc'
    state: 'present'
  when:
    - os_auth_pam_passwdqc_enable

- name: configure passwdqc and faillock via central system-auth config
  template:
    src: 'etc/pam.d/rhel_auth.j2'
    dest: '/etc/pam.d/system-auth-local'
    mode: '0640'
    owner: 'root'
    group: 'root'

- name: enable our config for system-auth
  file:
    src: /etc/pam.d/system-auth-local
    dest: /etc/pam.d/system-auth
    mode: '0640'
    owner: 'root'
    group: 'root'
    state: link
    force: true

- name: configure passwdqc and faillock via central password-auth config
  template:
    src: 'etc/pam.d/rhel_auth.j2'
    dest: '/etc/pam.d/password-auth-local'
    mode: '0640'
    owner: 'root'
    group: 'root'

- name: enable our config for password-auth
  file:
    src: /etc/pam.d/password-auth-local
    dest: /etc/pam.d/password-auth
    mode: '0640'
    owner: 'root'
    group: 'root'
    state: link
    force: true

- name: remove passwdqc
  yum:
    name: 'pam_passwdqc'
    state: 'absent'
  when:
    - not os_auth_pam_passwdqc_enable
